Fix display name html
PuzzleServer/mainpuzzleserver pull request #779
Opened 2023-03-14 08:17 UTC by digit01Wave

Remove usage of Html.DisplayNameFor and Html.DisplayFor except for items with [Display(...)] or [DisplayFormat(...)]

Addresses issue
#769

2023-03-14 17:23 UTC, tabascq requested changes

2023-03-14 17:23 UTC, tabascq commented on ServerCore/Pages/Puzzles/Feedback.cshtml
> +    <h4><b>Avg Fun Rating:</b> @Model.FunScore / @FeedbackModel.FeedbackMax</h4>
These two have a [DisplayFormat] attribute, so something was lost here.

2023-03-14 17:23 UTC, tabascq commented on ServerCore/Pages/Events/Delete.cshtml
> +            UrlString
You didn't break anything here, but it looks like something is off WRT UrlString and HomePartial as they do not match the dt-followed-by-dd pattern used by the other properties. Not an important fix as we rarely delete events anyway...

2023-03-15 19:22 UTC, digit01Wave commented on ServerCore/Pages/Puzzles/Feedback.cshtml
> +    <h4><b>Avg Fun Rating:</b> @Model.FunScore / @FeedbackModel.FeedbackMax</h4>
Ah good catch. Thanks

2023-03-16 08:25 UTC, tabascq approved these changes

2023-03-16 08:25 UTC, merged